spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8090

logging:
  level:
    org.springframework.security: DEBUG
    
jwt:
  key: 82822e69f51413f58606474ba4dd0919b1cb1875a611e46470afc9494c89b5cf
  expiration-seconds: 3600

cards:
  per-page: 10
  expire-check:  0 0 * * * *
  encryption:
    key: 1234567890123456
    iv-length: 12
    algorithm: AES/GCM/NoPadding
    tag-length: 128
  number:
    bin: 555555
    length: 16
    cache:
      batch: 10
      min: 10
      capacity: 100